### ISSUE TITLE
Failed to patch files

### ISSUE THREAD

**Issue by Tanddant** [itsmattkc/LEGOIslandRebuilder#10]
I'm running version 1.1 of the game installed in Danish, dosen't seem to be related to this issue though.

I get an error saying "Failed to patch files" - looking into the exception it's an access denied trying to get the file "C:\Users\danat\AppData\Local\Temp\LEGOIslandRebuilder\D3DRM.DLL" however the temp path "C:\Users\danat\AppData\Local\Temp\LEGOIslandRebuilder" dosen't exist, as it can be seen from the screenshot.

let me know if you need more info regarding the issue, or know the value of variables at a given time, I haven't had the time to look more at the code and try to figure out why the folder isn't being created.

![Anmærkning 2020-03-20 144717](https://user-images.githubusercontent.com/6947024/77169661-2d053a00-6aba-11ea-9e86-753c51cdac74.png)

![Anmærkning 2020-03-20 145227](https://user-images.githubusercontent.com/6947024/77169893-8bcab380-6aba-11ea-96e3-e5f0010b7fbb.png)

![Anmærkning 2020-03-20 145136](https://user-images.githubusercontent.com/6947024/77169769-5625ca80-6aba-11ea-885c-bcca28254775.png)

![Anmærkning 2020-03-20 145312](https://user-images.githubusercontent.com/6947024/77169910-91c09480-6aba-11ea-8230-01d9a4c8c0dc.png)

**Comment by TheWattsMan** [comment]
I'm having the same problem. Installed LEGO Island, closed the launcher, opened the patch tool, replaced all the music that has been remastered, hit run, and it worked, but I encountered graphics glitches because I hadn't switched to software rendering. After I closed the game, switched the rendering to software RGB, and tried to run the game via the patcher, at which point the patcher started throwing the "failed to patch files" error. I don't know where the program puts its logs or how to find the exception referred to by Tanddant, but I'm happy to forward them if I'm pointed to where they are.

**Comment by Tanddant** [comment]
@TheWattsMan it doesn't look like the program actually logs, I "just" cloned the source and ran it in debug mode with a breakpoint on the line that shows the errorbox.
It shouldn't be to much trouble if you're technical enclined, but if you're unable to do that

I guess I could implement some sort of logging if @itsmattkc would allow that, I couldn't find any documentation on how he wants other to help out with the project.

**Comment by itsmattkc** [comment]
Try the latest commit, it has improved directory handling as well as more informative messages and logging.

**Comment by Tanddant** [comment]
Issue seems to be the same:
![image](https://user-images.githubusercontent.com/6947024/77250226-cc573800-6c46-11ea-9d98-cbc9c5ff5946.png)

Log file attached here: 
[legoislandrebuilder.log](https://github.com/itsmattkc/LEGOIslandRebuilder/files/4365265/legoislandrebuilder.log)

**Comment by itsmattkc** [comment]
What happens when you delete the `C:\Users\danat\AppData\Local\Temp\LEGOIslandRebuilder` folder manually?

**Comment by Tanddant** [comment]
That got me further!

![image](https://user-images.githubusercontent.com/6947024/77250472-81d6bb00-6c48-11ea-9717-05cd72678c99.png)

The game crashed while loading (it normally works fine) - and then I'm back to the same error as in [the comment](https://github.com/itsmattkc/LEGOIslandRebuilder/issues/10#issuecomment-602198827) above.

**Comment by itsmattkc** [comment]
This error is at least somewhat expected, many of the international releases of LEGO Island have been recompiled and many of the patch offsets have been shifted around. 960669fd556fbcab5dea62ab0d21022df13b6fdf should add support for your version.

As for the other issue, what are the permissions of `C:\Users\danat\AppData\Local\Temp\LEGOIslandRebuilder\D3DRM.DLL`? Do you have ownership of the file?

**Comment by Tanddant** [comment]
The game works now, I still have to delete the files everytime, but it works - thank a ton for your great work

**Comment by Tanddant** [comment]
As for the D3DRM.DLL it's marked as "read only", from checking a few files in the folder it seems that it's the only file marked this way

**Comment by itsmattkc** [comment]
Ah I assume your D3DRM.DLL is from the CD, which might give it a read only attribute and cause the re-copy to fail. 7b6b2c446e96f088580f50885cdaf6cc32a36809 should fix this.

**Comment by Tanddant** [comment]
A simple fix for a simple problem - sure does work, again thanks a ton :-)
