### ISSUE TITLE
Not an issue but might be helpful

### ISSUE THREAD

**Issue by Kore-Development** [itsmattkc/LEGOIslandRebuilder#19]
If you change the releases from pre-release to release you can use this URL to download a file from the latest release instead of keeping a single release. Just making sure you know about this.
https://github.com/itsmattkc/LEGOIslandRebuilder/releases/latest/download/Rebuilder.exe

**Comment by Kore-Development** [comment]
It's 404 because there's only a pre-release and not a normal release

**Comment by itsmattkc** [comment]
I feel like the link we have is not hugely different and is good enough: https://github.com/itsmattkc/LEGOIslandRebuilder/releases/download/continuous/Rebuilder.exe
