### ISSUE TITLE
Rebuilder not working on Hardware Mode

### ISSUE THREAD

**Issue by Neorocket64** [itsmattkc/LEGOIslandRebuilder#22]
in hardware mode, it showed this error:
![image](https://user-images.githubusercontent.com/17949796/103343884-b1f89780-4abf-11eb-94b4-6d117cbd4f2c.png)

checking out Ramp emulation, i can conclude that "Flip Video Memory Page" made same error as above.
this is the setup that triggers it:
![image](https://user-images.githubusercontent.com/17949796/103344077-24697780-4ac0-11eb-9d51-e42ae7efab64.png)
"Draw 3D to Video Memory" option or none of those 2 will run the game, albeit 3d texture glitches.
other software modes will run the game good.

also running the game without the help of voodoo2 (cause it'll be glitchy on some 3d models with it, both Hardware without the Rebuilder and Software Mode)

current configs for Rebuilder:
![image](https://user-images.githubusercontent.com/17949796/103344663-cc337500-4ac1-11eb-8d60-4669d3fb9553.png)

Windows 10 Version 1909
installed the game using LEGO Island Alternate Installer
not sure if it really affects anything, but i used japanese locale.

**Comment by itsmattkc** [comment]
Sorry about the late reply on here. Were you trying to run LEGO Island windowed? Hardware mode will always fail in windowed mode.
