### ISSUE TITLE
Lego Island crashes in Hardware mode

### ISSUE THREAD

**Issue by athleti** [itsmattkc/LEGOIslandRebuilder#24]
Hi. So for the past 2 days i've tried getting Lego Island to work in Hardware mode. The game runs in RGB mode with and without rebuilder, but D3D Hal refuses to start with both Isle.exe and Rebuilder. I have DgVoodoo2 configured to the game, but when i try to start the game, the intro movies play like they should, but if i skip or watch the intro movies, i get a black screen, then it shows the Information Center for a split second, then it just crashes, with no error message. I don't know what is causing this, since a couple months ago, the game did work in Hardware mode with Dgvoodoo and Rebuilder. Can anyone help me? Thanks in advance.

And here are my Config.exe and Lego Island Rebuilder configurations. 

![Näyttökuva 2021-02-24 231009](https://user-images.githubusercontent.com/79606987/109066813-4e24d080-76f6-11eb-9b6e-796d9eb24ffa.png)

![Screenshot (14)](https://user-images.githubusercontent.com/79606987/109066835-53821b00-76f6-11eb-8845-07579dd97be2.png)

And BTW, i am using Dgvoodoo version 2.53, instead of 2.72 or basically the latest version, since i tried that first, and it didn't work, then i remembered that 2.53 worked, so i tried that, and it also failed.

**Comment by itsmattkc** [comment]
This doesn't sound strictly like a Rebuilder issue since you're having problems with just ISLE.EXE too. Have you tried running HAL without dgVoodoo at all?

**Comment by athleti** [comment]
@itsmattkc yes i did try running Hal without Dgvoodoo, it did launch, in that i got past the intro and could play the game, however, the graphics were glitched, such as infomaniacs face has a white square on it as opposed to his actual face. Basically just like in your Ultimate 98 pc video.

**Comment by itsmattkc** [comment]
Yeah understandable. What's your dgVoodoo configuration look like at the moment?

**Comment by athleti** [comment]
Here.

![Näyttökuva 2021-02-25 012312](https://user-images.githubusercontent.com/79606987/109079799-2179b480-7708-11eb-84ef-599e2551fe0a.png)

![Näyttökuva 2021-02-25 012340](https://user-images.githubusercontent.com/79606987/109079816-28a0c280-7708-11eb-891d-76d96dfa3ebd.png)

And also, i should have said, without voodoo, D3D hal is kind of weird for me, sometimes it's glitched up, but other times, it looks like it should, but i can't click the book. Which is a problem with Hal without Voodoo, right?

**Comment by itsmattkc** [comment]
Yeah D3D HAL has a lot of issues on modern PCs on its own.

Which D3DRM.DLL are you using? We recommend this one over the one provided on the disc: https://legoisland.org/download/d3drm.zip

**Comment by athleti** [comment]
I installed the game, which is btw, version 1.0 currently (i did also try 1.1), using Alternate installer, which copies it into the folder. But, i'll try that one and report back asap.

**Comment by athleti** [comment]
Well i'll be damned, it actually worked, so HAL works now and doesn't crash. Thanks!! =D

![Screenshot (15)](https://user-images.githubusercontent.com/79606987/109081152-7d453d00-770a-11eb-84d7-5c8573f1bd7b.png)

**Comment by itsmattkc** [comment]
Awesome, we might look into getting the newer D3DRM into the alternate installer to solve this for good. I'll go ahead and close this then

**Comment by Ramen2X** [comment]
@athleti The use of the newer d3drm.dll is now implemented into the Alternate Installer; so long as you use that to install the game from now on, you shouldn't have to run into this issue again.
