### ISSUE TITLE
README.md contains incorrect link to identifying game version.

### ISSUE THREAD

**Issue by Tekunalogy** [itsmattkc/LEGOIslandRebuilder#25]
Current link is to: https://www.legoisland.org/index.php/Lego_Island_Versions

Correct link should be: https://www.legoisland.org/wiki/index.php/LEGO_Island_Versions

**Comment by Ramen2X** [comment]
Fixed with 22b6a1f31c0596a7e3765385d1032c79e784820f. Thanks for the heads up!
