### ISSUE TITLE
Failed to copy files for patching.

### ISSUE THREAD

**Issue by Cheesegriller** [itsmattkc/LEGOIslandRebuilder#27]
![Error](https://i.ibb.co/KV61ftD/aaaa.png)

**Comment by itsmattkc** [comment]
Where are your game files located?

**Comment by Cheesegriller** [comment]
> 
> 
> Where are your game files located?

In my Libraries\Documents\Lego Island folder

**Comment by itsmattkc** [comment]
Can you show me LEGO Island's registry keys?

1. Open `regedit`
2. Browse to `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Mindscape\LEGO Island`
    - (or if your OS is 32-bit, `HKEY_LOCAL_MACHINE\SOFTWARE\Mindscape\LEGO Island`)
3. Screenshot

**Comment by Cheesegriller** [comment]
> 
> 
> Can you show me LEGO Island's registry keys?
> 
>     1. Open `regedit`
> 
>     2. Browse to `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Mindscape\LEGO Island`
>        
>        * (or if your OS is 32-bit, `HKEY_LOCAL_MACHINE\SOFTWARE\Mindscape\LEGO Island`)
> 
>     3. Screenshot

![LegoIslandRegedit](https://i.ibb.co/tB56XTh/lego-island.png)

**Comment by itsmattkc** [comment]
It would appear you installed LEGO Island to "C:\Program Files (x86)" and then moved the files to your "Documents" afterwards. Rebuilder uses that "diskpath" key in the registry to find the game (which is set by LEGO Island's installer). If you change "diskpath" to where you've moved the files to, then it will work (or alternatively you can run the installer again to the new location).
