### ISSUE TITLE
0xc0000135 error in Windows XP

### ISSUE THREAD

**Issue by seechenhao1** [itsmattkc/LEGOIslandRebuilder#33]
I'm trying to get rebuilder to run in a Windows XP VM, but I am getting the error "The application has failed to initialize properly (0xc0000135)"

**Comment by Ramen2X** [comment]
Is a version of .NET Framework installed on the virtual machine?

**Comment by seechenhao1** [comment]
no

**Comment by itsmattkc** [comment]
Sounds like that's the problem. See the README:

![image](https://user-images.githubusercontent.com/34096995/134126674-8c2d6092-c2f2-4b05-9683-1069ca821d9a.png)
