### ISSUE TITLE
Unhooked turn speed too slow by default

### ISSUE THREAD

**Issue by SuperfieldCU** [itsmattkc/LEGOIslandRebuilder#35]
We all know about LEGO Island's longstanding turn speed bug and how Rebuilder finally defeated it... except that unhooking the turn speed only guarantees that it will always be consistent. There's no reason to assume that doing so will set the speed to something that is "good". Sure, it's not an exact science to determine what speed the developers originally intended, but it's pretty clear that 20 unhooked quite a bit slower than 20 hooked at 15 FPS.

I found that 60 is a pretty good value for the unhooked speed. Regardless, I think there should be something that tells the user that the speed isn't necessarily "fixed" just because it's now unhooked, or maybe automatically setting the speed higher when the user turns on the unhooked speed in the Rebuilder.

**Comment by Ramen2X** [comment]
The turn speed unhooking patch in Rebuilder is an authentic representation of what the game would have felt like if the turning was implemented correctly by the original developers, which is the sole purpose of the patch. It does not modify any speed values on its own, it only performs the unhooking. The base speed was set by the original developers.

Ultimately, the speed of the turning is completely up to preference; we have a turning speed option for this exact purpose and experimenting with it until it is to your liking is encouraged.

**Comment by SuperfieldCU** [comment]
I actually disagree with the idea that the speed would've been kept at 20 if they had unhooked it prior to release. They set the speed to 20 because that's a good speed for the FPS that their target machines were capable of. If they had unhooked the turn speed, they would've seen that it suddenly became much slower and raised the value to compensate.
