### ISSUE TITLE
Lego Island Rebuilder is not starting. Appears on Processes List for one second and disappears.

### ISSUE THREAD

**Issue by mangoALCATRAZ** [itsmattkc/LEGOIslandRebuilder#38]
Hello.

I have a working installation of Lego Island installed on a Windows XP Service Pack 3 Virtual Machine running on VMWare Fusion on Mac OS X Catalina. My Windows XP installation currently has Microsoft .NET Framework 2.0 installed. 

I have Lego Island Rebuilder saved to a folder on my Desktop. Upon trying to launch, it appears on my Processes list for about one second before disappearing. No error message or anything.

**Comment by Ramen2X** [comment]
Is there anything else besides .NET Framework, LEGO Island, and Rebuilder installed on the VM?

**Comment by mangoALCATRAZ** [comment]
> Is there anything else besides .NET Framework, LEGO Island, and Rebuilder installed on the VM?

No. I had previously tried to install the latest available version of .NET Framework that was compatible with WinXP SP3 but this didn't seem to work. I uninstalled this and installed .NET Framework 2.0.

**Comment by Ramen2X** [comment]
That's interesting - any version of .NET Framework that is 2.0 or higher should work with Rebuilder. Usually, if the fault has something to do with .NET Framework, it will throw a visible error.

Did you get the same result using a newer version of .NET Framework?(Rebuilder closing almost immediately?)

**Comment by Ramen2X** [comment]
I'm closing this partly due to inactivity but mostly because the .NET version of Rebuilder is no longer supported and this sounds like it could be a .NET Framework or otherwise a general setup issue. If any issues arise with the new version of Rebuilder, feel free to open a new issue.
