### ISSUE TITLE
graphical glitches when starting LEGO Island in windowed mode

### ISSUE THREAD

**Issue by MacOS-9** [itsmattkc/LEGOIslandRebuilder#39]
hello anyone who is reading this,
when i enable windowed mode in LEGO Island rebuilder and run the game, this is what i get:
![image](https://user-images.githubusercontent.com/62616943/155945018-081f41dd-3ad7-4cc2-90a2-9e3a5798b714.png)
i have no idea why, but i do know that i am using windows 7 ultimate (x86), all the exe's except Uninst.exe in the C:\Program Files\LEGO Island directory are set to compatibility mode with windows xp service pack 3 selected, and this does not happen in fullscreen mode
edit: without the compatibility mode the game refuses to even run no matter what i select in the rebuilder
edit 2: without compatibility mode the game did not run but now it does without compatibility mode idk why

**Comment by itsmattkc** [comment]
https://www.legoisland.org/wiki/index.php/Windowed_Mode#In_windowed_mode.2C_the_background_textures_are_missing_and_everything_is_blue
