### ISSUE TITLE
Failed to Create Process with Error 0x2e4

### ISSUE THREAD

**Issue by CrazySeanDX** [itsmattkc/LEGOIslandRebuilder#43]
I deleted the file you said to delete originally, but I still can't get Rebuilder to start Lego Island with the fixes in question cause of the aforementioned error in the title. I tried doing the solution that involved deleting a folder in the Temp section of AppData/Local, but there wasn't any folder like that. I'm sorry to bother about this again, but I need help figuring this out, and I made sure to check the README this time.

Edit: I got it to run(compatibility mode was the issue), but the mouse is still missing. It also isn't 60FPS like before, for some reason.

**Comment by itsmattkc** [comment]
Yeah 2e4 is insufficient permissions so, as you discovered, make sure compatibility modes are off and it's not running as administrator.
