### ISSUE TITLE
Holding the Ctrl key speeds up the turning speed

### ISSUE THREAD

**Issue by mrpenguinb** [itsmattkc/LEGOIslandRebuilder#46]
While in-game, you can switch between fast and slow turning. Is this part of LEGOIslandRebuilder, a bug, or intended vanilla behaviour?

Also changing the turning speed with Ctrl isn't as fast as when it's unhooked.

**Comment by itsmattkc** [comment]
That is part of the original game. It's an undocumented "run" button.
