### ISSUE TITLE
"Failed to create process with error 0x2e4" inmediately when clicking run.

### ISSUE THREAD

**Issue by SimplyAlonso** [itsmattkc/LEGOIslandRebuilder#47]
Just installed LEGO Island through the alt installer, used Lego Island Rebuilder, and got this. No idea what went wrong. Help?
![image](https://simplyalonso.neocities.org/IjGcIem1m3.png)

**Comment by Ramen2X** [comment]
Is LEGO Island set to run as administrator? If so, you must either grant Rebuilder administrator privileges or remove LEGO Island's admin privileges.

**Comment by itsmattkc** [comment]
Latest commit will reconfigure compat modes to function correctly
