### ISSUE TITLE
The game doesn't start with the Rebuilder

### ISSUE THREAD

**Issue by undefinedCat** [itsmattkc/LEGOIslandRebuilder#55]
I installed the game to the I:\ drive because the C:\ drive is almost filled up. And Rebuilder doesn't start the game from there. Maybe I can compile a version specifically for me?

**Comment by itsmattkc** [comment]
Rebuilder uses whatever value is in `HKLM\Software\Mindscape\LEGO Island\diskpath` (or `HKLM\Software\WOW6432Node\Mindscape\LEGO Island\diskpath` on 64-bit systems), which is set by the installer. Check what value has been set there.

**Comment by undefinedCat** [comment]
I've reinstalled the game to C:\ and I see this in `regedit`:
![image](https://user-images.githubusercontent.com/73075315/201487902-fa7e26f5-8421-4828-8b41-58cd621d1277.png)

**Comment by itsmattkc** [comment]
The `diskpath` thing was only relevant while it was installed on `I:\`. Are you implying you're still having issues despite that no longer being the case?

**Comment by undefinedCat** [comment]
@itsmattkc
Yeah, but I'm typing from my phone, so I can't show or tell any info from my PC.
