### ISSUE TITLE
LEGO Island not starting

### ISSUE THREAD

**Issue by bimbo1989** [itsmattkc/LEGOIslandRebuilder#56]
Hi!
First of all thank you for this awesome tool.
I have a problem that I think might be related to the Alternate Installer, but the repo is read-only so I can't ask there. I'm asking you because you are the biggest experts and maybe you can help me anyway.
I installed LEGO Island fully on my hard drive, but when I try to launch it, be it via the Rebuilder or the normal EXE nothing happens. Actually, you can see the process in the Task Manager, but nothing else. I only noticed that, when I launch it, a .log file gets created named "DDrawCompat-ISLE.log". This is the content of the file

> 10:59:14.224 Process path: D:\Giochi\LEGO Island\ISLE.EXE
> 10:59:14.224 Environment variable __COMPAT_LAYER = "HighDpiAware"
> 10:59:14.224 Loading DDrawCompat statically from D:\Giochi\LEGO Island\DDRAW.dll

And this is the content of regedit
![image](https://user-images.githubusercontent.com/13590149/207565997-7d85e6c6-9d8c-45e9-990a-d12185247e21.png)

Thank you in advance!

**Comment by Ramen2X** [comment]
The Alternate Installer is currently bundled with a version of DDrawCompat that is outdated and doesn't seem to function on recent versions of Windows 11. Unfortunately, this can't be addressed since the installer's repository has been archived. If you remove ddraw.dll from the game directory (or replace it with a newer version of DDrawCompat), it should boot.

**Comment by bimbo1989** [comment]
Hi @Ramen2X , thank you for your answer. I already tried what you said, but I get a "No disc inserted" error. If I try and mount the disc, I get "Disc verification error (3)"

**Comment by Ramen2X** [comment]
Interesting... by any chance, is this the Italian version of the game? If so, replace the ISLE.EXE in your game directory with one from another version (any version should work).

**Comment by bimbo1989** [comment]
@Ramen2X that was the issue! I had no idea the italian version worked differently 😅

I have one last problem: the game starts but looks like this
![image](https://user-images.githubusercontent.com/13590149/208442758-da095f99-73c3-4c47-be75-fe67c047a049.png)
I have already tried tinkering with all the settings, with no better results. Also, the beginning video that is supposed to show the cascade of bricks composing the LEGO logo does not show. The audio can be heard though.

**Comment by bimbo1989** [comment]
@Ramen2X solved! I had to put the new ddraw.dll there. Thank you for everything!

**Comment by Ramen2X** [comment]
> @Ramen2X that was the issue! I had no idea the italian version worked differently 😅

Yeah, it's very strange but the Italian release's executable is protected unlike any other version of the game. We should probably handle this discrepancy in Rebuilder itself to prevent further issues like this, but as of now swapping it out with a normal unprotected executable is the best course of action.

Glad you got everything working!

**Comment by Ramen2X** [comment]
Heads up: the latest Rebuilder should now automatically detect these protected executables and inform the user about their incompatibility with the tool.
