### ISSUE TITLE
Lego Island can't detect directx

### ISSUE THREAD

**Issue by NetheriteOfficial** [itsmattkc/LEGOIslandRebuilder#63]
I've wanted to make Windows 95 VM and play some games, so i installed lego island and runned it but i got error:
![image](https://github.com/itsmattkc/LEGOIslandRebuilder/assets/108182503/50994b40-a94c-4a06-8adb-d2fb4d1cce67)
Compatibility mode is set to VMware 5.x

**Comment by itsmattkc** [comment]
The message is pretty self-explanatory; you need to install DirectX 5. The LEGO Island installer should have prompted you to do this. You can either run the installer again and agree to install DirectX, or launch the DirectX installer separately at `D:\redist\directx\setup.exe`.
