### ISSUE TITLE
GitHub CI?

### ISSUE THREAD

**Issue by GL513** [itsmattkc/LEGOIslandRebuilder#65]
Set up continuous integration to build EXE files for quick access?

**Comment by TheTechRobo** [comment]
is that not what https://github.com/itsmattkc/LEGOIslandRebuilder/releases/tag/continuous is for?

**Comment by itsmattkc** [comment]
Yeah we pretty clearly already have it.

**Comment by GL513** [comment]
Crap sorry lol I was on the mobile app and didn't quite take the time to look. My bad.
