### ISSUE TITLE
Elevator Swimming Scene Glitch When I Turn On Use Only WASD Keys for Movement Glitch

### ISSUE THREAD

**Issue by AjTech1089** [itsmattkc/LEGOIslandRebuilder#71]
When I turn on Use WASD Keys in Lego Island, I accidentally press one of the arrow keys. When I press the keys by accident, there is this weird elevator swimming scene glitch that can be seen from the information center. This can also be seen always everywhere you go.

**Comment by Ramen2X** [comment]
This is because you activated Debug Mode either using the patch that forces it on, or by typing OGEL. Debug Mode's keys are typically mapped to WASD, but they are remapped to the arrow keys when the WASD patch is enabled.
