### ISSUE TITLE
Textures randomly disappeared, replaced with bland colors reflecting the texture's color [Direct3D HAL]

### ISSUE THREAD

**Issue by 92971** [itsmattkc/LEGOIslandRebuilder#72]
### **The issue is, when I start LEGO Island now with my following preferences (see below), some textures don't seem to render properly.**

I can still play the game FINE, but the game just....... doesn't look right.

Just to fill/clear this up, starting the game before was fine, all the textures were there.

I have also [followed all the steps](https://www.legoisland.org/wiki/index.php?title=Compatibility_Issues) necessary to play the game on my modern PC. RGB Emulation? Check. [d3drm.dll](https://legoisland.org/download/d3drm.zip)? Absolutely. dgVoodoo2? Yup.

But ever since, I did modify the settings a little bit. I now use [Direct3D HAL](https://github.com/itsmattkc/LEGOIslandRebuilder/issues/68) instead of RGB Emulation.

I am on Windows 11 21H2, 11th Gen Intel Core i5 with Integrated Graphics, DirectX 12, dgVoodoo2 2.8.2, 8GB DDR4 RAM, 256GB M.2 NVMe SSD and a 13-inch screen.

My preferences are:
 - Speed Up Startup: Enabled
 - Redirect Save Files to %APPDATA%: Enabled
 - Exit Crash Fix: Enabled
 - Unhook Turning From Frame Rate
 - Direct3D Device: Direct3D HAL
 - FPS Cap: Default
 - Draw Cursor: Disabled
 - Model Quality: High

I am using the C++ version of Rebuilder, and yes, this issue is similar to these issues:
 - [#53](https://github.com/itsmattkc/LEGOIslandRebuilder/issues/53)
 - [#50](https://github.com/itsmattkc/LEGOIslandRebuilder/issues/50)
 - [#39](https://github.com/itsmattkc/LEGOIslandRebuilder/issues/39)
 
 I can confirm this is not an issue with Direct3D HAL. Even going back to RGB Emulation, the textures still do not appear,
 
![Screenshot 2023-08-07 110647](https://github.com/itsmattkc/LEGOIslandRebuilder/assets/136334479/5d1f2439-715d-431b-b1b5-6f051d06a963)

Here are some photos:

LEGO Island now:

![Screenshot 2023-08-07 104653](https://github.com/itsmattkc/LEGOIslandRebuilder/assets/136334479/d9f92d09-51e3-4be8-93fd-d6fd8abfb4ae)

LEGO Island before:

![Screenshot 2023-08-07 104946](https://github.com/itsmattkc/LEGOIslandRebuilder/assets/136334479/75137ebe-971c-43e0-8b75-c3d97cb05e77)

**Comment by CatOfBlades** [comment]
I had the exact same texture issues. Try running the rebuilder with compatibility for windowsXP sp2 and run as administrator.
That solved missing textures for me.
