### ISSUE TITLE
textures are pink and black

### ISSUE THREAD

**Issue by Fridmii** [itsmattkc/LEGOIslandRebuilder#77]
ah sh*t, here we go again

Ive done my research on these forms, ive tried the fixes, doesnt work 🙃
would be appreciated if you can help, thanks.

some images:
<img width="304" alt="Screenshot 2023-12-06 191200" src="https://github.com/itsmattkc/LEGOIslandRebuilder/assets/153127323/6f28519b-af49-4c3e-beb0-7abeb3ba346f">
<img width="280" alt="Screenshot 2023-12-06 193830" src="https://github.com/itsmattkc/LEGOIslandRebuilder/assets/153127323/2cee212a-c3fd-4f4f-96d6-1b030ce305e5">
<img width="276" alt="Screenshot 2023-12-06 193848" src="https://github.com/itsmattkc/LEGOIslandRebuilder/assets/153127323/4527856b-4df1-4f63-96a4-1e824a0be7a8">

**Comment by itsmattkc** [comment]
Try enabling "Draw 3D to Video Memory"

**Comment by Fridmii** [comment]
i tired that, didnt work :(

thanks tho :)

**Comment by Fridmii** [comment]
NOTE: just fixed it using ramp emulation,

**Comment by itsmattkc** [comment]
Use RGB Emulation, not Ramp.

**Comment by Fridmii** [comment]
i switched to rgb emulation, since ramp didnt give me ANY working textures, any fixes?

**Comment by Ramen2X** [comment]
Closing due to common issue + inactivity, please reopen if you have any more questions.
