### ISSUE TITLE
information centre is mostly blank

### ISSUE THREAD

**Issue by UckyDuckyYT** [itsmattkc/LEGOIslandRebuilder#78]
Info centre is mostly blank besides 2 flowers and the info centre man.
![Screenshot (2475)](https://github.com/itsmattkc/LEGOIslandRebuilder/assets/84649358/f0a24c78-d3db-4e43-aab9-8d6459e87caf)

**Comment by itsmattkc** [comment]
https://www.legoisland.org/wiki/Windowed_Mode#Missing_bitmaps
