### ISSUE TITLE
virustotal flaging Lego island rebuilder as a virus

### ISSUE THREAD

**Issue by ihatesignins** [itsmattkc/LEGOIslandRebuilder#80]
virus total found 4 viruses within Lego Island rebuilder, the rebuilder was downloaded under downloads on README.md

[https://www.virustotal.com/gui/file/267db960dc7c5fc9dc944feab426ef8e0e0158fb429e0bd198a61ef4057f8157](url)
here is the link to the virus total scan

**Comment by itsmattkc** [comment]
False positive, likely due to our usage of DLL injection. You can safely ignore it.
