### ISSUE TITLE
executable marked as dangerous.

### ISSUE THREAD

**Issue by Scrimbylol** [itsmattkc/LEGOIslandRebuilder#81]
### Hello, I was planning on playing lego island, and I know i'd need to use the rebuilder tool
so I downloaded the tool off the github (as one would) and when I downloaded it, windows defender marked it as a trojan and deleted it

![whatwhy](https://github.com/isledecomp/LEGOIslandRebuilder/assets/153399487/0ff5d765-d049-465b-9c31-53899781245a)

and I'm not really sure what to do, I can't seem to allow it in time before it gets deleted.
I assume that the program is safe, so I don't see why it would do this.
if there are any ways I could fix this, do tell me. thank you!

**Comment by Ramen2X** [comment]
False positive, probably due to our use of DLL injection to modify LEGO Island's code at runtime. Rebuilder is fully open source, this can be safely whitelisted and ignored.
